# Streamlit Configuration
# Clean configuration without deprecated options

[global]
developmentMode = false

[server]
port = 8501
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#F7931A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"